name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, windows]
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild Path
        run: |
          $msbuildPath = "${env:ProgramFiles}\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
          if (-not (Test-Path $msbuildPath)) {
            $msbuildPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
          }
          if (-not (Test-Path $msbuildPath)) {
            $msbuildPath = "${env:ProgramFiles(x86)}\MSBuild\14.0\Bin\MSBuild.exe"
          }
          echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore Packages
        run: nuget restore Source\RW-MassAffect.sln

      - name: Build solution
        run: |
          & "$env:MSBUILD_PATH" Source\RW-MassAffect.sln -t:rebuild -property:Configuration=Debug
        shell: pwsh