name: release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: [self-hosted, windows]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: RW-MassAffect-dll
          path: ./artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      
      - name: Prepare Assemblies folder
        run: |
          New-Item -ItemType Directory -Force -Path Assemblies
          Copy-Item ./artifacts/RW-MassAffect.dll Assemblies/
        shell: powershell
      
      - name: Create Release Zip
        run: |
          # Create zip excluding unwanted directories and files
          $excludePatterns = @('*.git*', '.github', '.gitignore', '.vscode', '.vs', 'Source\bin', 'Source\obj', 'artifacts')
          $allItems = Get-ChildItem -Recurse | Where-Object { 
            $item = $_
            -not ($excludePatterns | Where-Object { $item.FullName -like "*$_*" })
          } | ForEach-Object { $_.FullName }
          
          if ($allItems) {
            Compress-Archive -Path $allItems -DestinationPath MassAffect-Release.zip -Force
          } else {
            Write-Host "No items found to compress"
          }
        shell: powershell
